### PR TITLE
Minor UI Changes to Index.vue

### PR DESCRIPTION
**Pull request by TaiOGU**
- Changed buttons so they match sizes
- Changed the background to be a GIF that is consistent with that used in the upcoming rareweave commercial

This overall results in a cleaner look IMO.

Let me know if you would like absolutely anything fixed/more info.

Thanks.

### CODE REVIEW

**Comment by TaiOGU** [comment]
As requested I'm changing it to a webp

**Comment by TaiOGU** [comment]
Changed!

**Review by ducksquaddd — APPROVED** [review]
Looks good to me

**Comment by TaiOGU** [comment]
@angrymouse

**Review by angrymouse — APPROVED** [review]

**Pull request merged**
